/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface CelerLedgerInterface extends Interface {
  functions: {
    renounceOwnership: TypedFunctionDescription<{ encode([]: []): string }>;

    owner: TypedFunctionDescription<{ encode([]: []): string }>;

    isOwner: TypedFunctionDescription<{ encode([]: []): string }>;

    transferOwnership: TypedFunctionDescription<{
      encode([newOwner]: [string]): string;
    }>;

    setBalanceLimits: TypedFunctionDescription<{
      encode([_tokenAddrs, _limits]: [string[], BigNumberish[]]): string;
    }>;

    disableBalanceLimits: TypedFunctionDescription<{ encode([]: []): string }>;

    enableBalanceLimits: TypedFunctionDescription<{ encode([]: []): string }>;

    openChannel: TypedFunctionDescription<{
      encode([_openRequest]: [Arrayish]): string;
    }>;

    deposit: TypedFunctionDescription<{
      encode([_channelId, _receiver, _transferFromAmount]: [
        Arrayish,
        string,
        BigNumberish
      ]): string;
    }>;

    depositInBatch: TypedFunctionDescription<{
      encode([_channelIds, _receivers, _transferFromAmounts]: [
        Arrayish[],
        string[],
        BigNumberish[]
      ]): string;
    }>;

    snapshotStates: TypedFunctionDescription<{
      encode([_signedSimplexStateArray]: [Arrayish]): string;
    }>;

    intendWithdraw: TypedFunctionDescription<{
      encode([_channelId, _amount, _recipientChannelId]: [
        Arrayish,
        BigNumberish,
        Arrayish
      ]): string;
    }>;

    confirmWithdraw: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    vetoWithdraw: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    cooperativeWithdraw: TypedFunctionDescription<{
      encode([_cooperativeWithdrawRequest]: [Arrayish]): string;
    }>;

    intendSettle: TypedFunctionDescription<{
      encode([_signedSimplexStateArray]: [Arrayish]): string;
    }>;

    clearPays: TypedFunctionDescription<{
      encode([_channelId, _peerFrom, _payIdList]: [
        Arrayish,
        string,
        Arrayish
      ]): string;
    }>;

    confirmSettle: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    cooperativeSettle: TypedFunctionDescription<{
      encode([_settleRequest]: [Arrayish]): string;
    }>;

    migrateChannelTo: TypedFunctionDescription<{
      encode([_migrationRequest]: [Arrayish]): string;
    }>;

    migrateChannelFrom: TypedFunctionDescription<{
      encode([_fromLedgerAddr, _migrationRequest]: [string, Arrayish]): string;
    }>;

    getSettleFinalizedTime: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getTokenContract: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getTokenType: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getChannelStatus: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getCooperativeWithdrawSeqNum: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getTotalBalance: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getBalanceMap: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getChannelMigrationArgs: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getPeersMigrationInfo: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getDisputeTimeout: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getMigratedTo: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getStateSeqNumMap: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getTransferOutMap: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getNextPayIdListHashMap: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getLastPayResolveDeadlineMap: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getPendingPayOutMap: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getWithdrawIntent: TypedFunctionDescription<{
      encode([_channelId]: [Arrayish]): string;
    }>;

    getChannelStatusNum: TypedFunctionDescription<{
      encode([_channelStatus]: [BigNumberish]): string;
    }>;

    getEthPool: TypedFunctionDescription<{ encode([]: []): string }>;

    getPayRegistry: TypedFunctionDescription<{ encode([]: []): string }>;

    getCelerWallet: TypedFunctionDescription<{ encode([]: []): string }>;

    getBalanceLimit: TypedFunctionDescription<{
      encode([_tokenAddr]: [string]): string;
    }>;

    getBalanceLimitsEnabled: TypedFunctionDescription<{
      encode([]: []): string;
    }>;
  };

  events: {
    OwnershipTransferred: TypedEventDescription<{
      encodeTopics([previousOwner, newOwner]: [
        string | null,
        string | null
      ]): string[];
    }>;

    OpenChannel: TypedEventDescription<{
      encodeTopics([
        channelId,
        tokenType,
        tokenAddress,
        peerAddrs,
        initialDeposits
      ]: [Arrayish | null, null, string | null, null, null]): string[];
    }>;

    Deposit: TypedEventDescription<{
      encodeTopics([channelId, peerAddrs, deposits, withdrawals]: [
        Arrayish | null,
        null,
        null,
        null
      ]): string[];
    }>;

    SnapshotStates: TypedEventDescription<{
      encodeTopics([channelId, seqNums]: [Arrayish | null, null]): string[];
    }>;

    IntendSettle: TypedEventDescription<{
      encodeTopics([channelId, seqNums]: [Arrayish | null, null]): string[];
    }>;

    ClearOnePay: TypedEventDescription<{
      encodeTopics([channelId, payId, peerFrom, amount]: [
        Arrayish | null,
        Arrayish | null,
        string | null,
        null
      ]): string[];
    }>;

    ConfirmSettle: TypedEventDescription<{
      encodeTopics([channelId, settleBalance]: [
        Arrayish | null,
        null
      ]): string[];
    }>;

    ConfirmSettleFail: TypedEventDescription<{
      encodeTopics([channelId]: [Arrayish | null]): string[];
    }>;

    IntendWithdraw: TypedEventDescription<{
      encodeTopics([channelId, receiver, amount]: [
        Arrayish | null,
        string | null,
        null
      ]): string[];
    }>;

    ConfirmWithdraw: TypedEventDescription<{
      encodeTopics([
        channelId,
        withdrawnAmount,
        receiver,
        recipientChannelId,
        deposits,
        withdrawals
      ]: [
        Arrayish | null,
        null,
        string | null,
        Arrayish | null,
        null,
        null
      ]): string[];
    }>;

    VetoWithdraw: TypedEventDescription<{
      encodeTopics([channelId]: [Arrayish | null]): string[];
    }>;

    CooperativeWithdraw: TypedEventDescription<{
      encodeTopics([
        channelId,
        withdrawnAmount,
        receiver,
        recipientChannelId,
        deposits,
        withdrawals,
        seqNum
      ]: [
        Arrayish | null,
        null,
        string | null,
        Arrayish | null,
        null,
        null,
        null
      ]): string[];
    }>;

    CooperativeSettle: TypedEventDescription<{
      encodeTopics([channelId, settleBalance]: [
        Arrayish | null,
        null
      ]): string[];
    }>;

    MigrateChannelTo: TypedEventDescription<{
      encodeTopics([channelId, newLedgerAddr]: [
        Arrayish | null,
        string | null
      ]): string[];
    }>;

    MigrateChannelFrom: TypedEventDescription<{
      encodeTopics([channelId, oldLedgerAddr]: [
        Arrayish | null,
        string | null
      ]): string[];
    }>;
  };
}

export class CelerLedger extends Contract {
  connect(signerOrProvider: Signer | Provider | string): CelerLedger;
  attach(addressOrName: string): CelerLedger;
  deployed(): Promise<CelerLedger>;

  on(event: EventFilter | string, listener: Listener): CelerLedger;
  once(event: EventFilter | string, listener: Listener): CelerLedger;
  addListener(eventName: EventFilter | string, listener: Listener): CelerLedger;
  removeAllListeners(eventName: EventFilter | string): CelerLedger;
  removeListener(eventName: any, listener: Listener): CelerLedger;

  interface: CelerLedgerInterface;

  functions: {
    renounceOwnership(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    owner(): Promise<string>;

    isOwner(): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setBalanceLimits(
      _tokenAddrs: string[],
      _limits: BigNumberish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    disableBalanceLimits(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    enableBalanceLimits(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    openChannel(
      _openRequest: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    deposit(
      _channelId: Arrayish,
      _receiver: string,
      _transferFromAmount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    depositInBatch(
      _channelIds: Arrayish[],
      _receivers: string[],
      _transferFromAmounts: BigNumberish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    snapshotStates(
      _signedSimplexStateArray: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    intendWithdraw(
      _channelId: Arrayish,
      _amount: BigNumberish,
      _recipientChannelId: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    confirmWithdraw(
      _channelId: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    vetoWithdraw(
      _channelId: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    cooperativeWithdraw(
      _cooperativeWithdrawRequest: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    intendSettle(
      _signedSimplexStateArray: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    clearPays(
      _channelId: Arrayish,
      _peerFrom: string,
      _payIdList: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    confirmSettle(
      _channelId: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    cooperativeSettle(
      _settleRequest: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    migrateChannelTo(
      _migrationRequest: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    migrateChannelFrom(
      _fromLedgerAddr: string,
      _migrationRequest: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getSettleFinalizedTime(_channelId: Arrayish): Promise<BigNumber>;

    getTokenContract(_channelId: Arrayish): Promise<string>;

    getTokenType(_channelId: Arrayish): Promise<number>;

    getChannelStatus(_channelId: Arrayish): Promise<number>;

    getCooperativeWithdrawSeqNum(_channelId: Arrayish): Promise<BigNumber>;

    getTotalBalance(_channelId: Arrayish): Promise<BigNumber>;

    getBalanceMap(
      _channelId: Arrayish
    ): Promise<{
      0: string[];
      1: BigNumber[];
      2: BigNumber[];
    }>;

    getChannelMigrationArgs(
      _channelId: Arrayish
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
      2: string;
      3: BigNumber;
    }>;

    getPeersMigrationInfo(
      _channelId: Arrayish
    ): Promise<{
      0: string[];
      1: BigNumber[];
      2: BigNumber[];
      3: BigNumber[];
      4: BigNumber[];
      5: BigNumber[];
    }>;

    getDisputeTimeout(_channelId: Arrayish): Promise<BigNumber>;

    getMigratedTo(_channelId: Arrayish): Promise<string>;

    getStateSeqNumMap(
      _channelId: Arrayish
    ): Promise<{
      0: string[];
      1: BigNumber[];
    }>;

    getTransferOutMap(
      _channelId: Arrayish
    ): Promise<{
      0: string[];
      1: BigNumber[];
    }>;

    getNextPayIdListHashMap(
      _channelId: Arrayish
    ): Promise<{
      0: string[];
      1: string[];
    }>;

    getLastPayResolveDeadlineMap(
      _channelId: Arrayish
    ): Promise<{
      0: string[];
      1: BigNumber[];
    }>;

    getPendingPayOutMap(
      _channelId: Arrayish
    ): Promise<{
      0: string[];
      1: BigNumber[];
    }>;

    getWithdrawIntent(
      _channelId: Arrayish
    ): Promise<{
      0: string;
      1: BigNumber;
      2: BigNumber;
      3: string;
    }>;

    getChannelStatusNum(_channelStatus: BigNumberish): Promise<BigNumber>;

    getEthPool(): Promise<string>;

    getPayRegistry(): Promise<string>;

    getCelerWallet(): Promise<string>;

    getBalanceLimit(_tokenAddr: string): Promise<BigNumber>;

    getBalanceLimitsEnabled(): Promise<boolean>;
  };

  renounceOwnership(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  owner(): Promise<string>;

  isOwner(): Promise<boolean>;

  transferOwnership(
    newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setBalanceLimits(
    _tokenAddrs: string[],
    _limits: BigNumberish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  disableBalanceLimits(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  enableBalanceLimits(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  openChannel(
    _openRequest: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  deposit(
    _channelId: Arrayish,
    _receiver: string,
    _transferFromAmount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  depositInBatch(
    _channelIds: Arrayish[],
    _receivers: string[],
    _transferFromAmounts: BigNumberish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  snapshotStates(
    _signedSimplexStateArray: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  intendWithdraw(
    _channelId: Arrayish,
    _amount: BigNumberish,
    _recipientChannelId: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  confirmWithdraw(
    _channelId: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  vetoWithdraw(
    _channelId: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  cooperativeWithdraw(
    _cooperativeWithdrawRequest: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  intendSettle(
    _signedSimplexStateArray: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  clearPays(
    _channelId: Arrayish,
    _peerFrom: string,
    _payIdList: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  confirmSettle(
    _channelId: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  cooperativeSettle(
    _settleRequest: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  migrateChannelTo(
    _migrationRequest: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  migrateChannelFrom(
    _fromLedgerAddr: string,
    _migrationRequest: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getSettleFinalizedTime(_channelId: Arrayish): Promise<BigNumber>;

  getTokenContract(_channelId: Arrayish): Promise<string>;

  getTokenType(_channelId: Arrayish): Promise<number>;

  getChannelStatus(_channelId: Arrayish): Promise<number>;

  getCooperativeWithdrawSeqNum(_channelId: Arrayish): Promise<BigNumber>;

  getTotalBalance(_channelId: Arrayish): Promise<BigNumber>;

  getBalanceMap(
    _channelId: Arrayish
  ): Promise<{
    0: string[];
    1: BigNumber[];
    2: BigNumber[];
  }>;

  getChannelMigrationArgs(
    _channelId: Arrayish
  ): Promise<{
    0: BigNumber;
    1: BigNumber;
    2: string;
    3: BigNumber;
  }>;

  getPeersMigrationInfo(
    _channelId: Arrayish
  ): Promise<{
    0: string[];
    1: BigNumber[];
    2: BigNumber[];
    3: BigNumber[];
    4: BigNumber[];
    5: BigNumber[];
  }>;

  getDisputeTimeout(_channelId: Arrayish): Promise<BigNumber>;

  getMigratedTo(_channelId: Arrayish): Promise<string>;

  getStateSeqNumMap(
    _channelId: Arrayish
  ): Promise<{
    0: string[];
    1: BigNumber[];
  }>;

  getTransferOutMap(
    _channelId: Arrayish
  ): Promise<{
    0: string[];
    1: BigNumber[];
  }>;

  getNextPayIdListHashMap(
    _channelId: Arrayish
  ): Promise<{
    0: string[];
    1: string[];
  }>;

  getLastPayResolveDeadlineMap(
    _channelId: Arrayish
  ): Promise<{
    0: string[];
    1: BigNumber[];
  }>;

  getPendingPayOutMap(
    _channelId: Arrayish
  ): Promise<{
    0: string[];
    1: BigNumber[];
  }>;

  getWithdrawIntent(
    _channelId: Arrayish
  ): Promise<{
    0: string;
    1: BigNumber;
    2: BigNumber;
    3: string;
  }>;

  getChannelStatusNum(_channelStatus: BigNumberish): Promise<BigNumber>;

  getEthPool(): Promise<string>;

  getPayRegistry(): Promise<string>;

  getCelerWallet(): Promise<string>;

  getBalanceLimit(_tokenAddr: string): Promise<BigNumber>;

  getBalanceLimitsEnabled(): Promise<boolean>;

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    OpenChannel(
      channelId: Arrayish | null,
      tokenType: null,
      tokenAddress: string | null,
      peerAddrs: null,
      initialDeposits: null
    ): EventFilter;

    Deposit(
      channelId: Arrayish | null,
      peerAddrs: null,
      deposits: null,
      withdrawals: null
    ): EventFilter;

    SnapshotStates(channelId: Arrayish | null, seqNums: null): EventFilter;

    IntendSettle(channelId: Arrayish | null, seqNums: null): EventFilter;

    ClearOnePay(
      channelId: Arrayish | null,
      payId: Arrayish | null,
      peerFrom: string | null,
      amount: null
    ): EventFilter;

    ConfirmSettle(channelId: Arrayish | null, settleBalance: null): EventFilter;

    ConfirmSettleFail(channelId: Arrayish | null): EventFilter;

    IntendWithdraw(
      channelId: Arrayish | null,
      receiver: string | null,
      amount: null
    ): EventFilter;

    ConfirmWithdraw(
      channelId: Arrayish | null,
      withdrawnAmount: null,
      receiver: string | null,
      recipientChannelId: Arrayish | null,
      deposits: null,
      withdrawals: null
    ): EventFilter;

    VetoWithdraw(channelId: Arrayish | null): EventFilter;

    CooperativeWithdraw(
      channelId: Arrayish | null,
      withdrawnAmount: null,
      receiver: string | null,
      recipientChannelId: Arrayish | null,
      deposits: null,
      withdrawals: null,
      seqNum: null
    ): EventFilter;

    CooperativeSettle(
      channelId: Arrayish | null,
      settleBalance: null
    ): EventFilter;

    MigrateChannelTo(
      channelId: Arrayish | null,
      newLedgerAddr: string | null
    ): EventFilter;

    MigrateChannelFrom(
      channelId: Arrayish | null,
      oldLedgerAddr: string | null
    ): EventFilter;
  };

  estimate: {
    renounceOwnership(): Promise<BigNumber>;

    owner(): Promise<BigNumber>;

    isOwner(): Promise<BigNumber>;

    transferOwnership(newOwner: string): Promise<BigNumber>;

    setBalanceLimits(
      _tokenAddrs: string[],
      _limits: BigNumberish[]
    ): Promise<BigNumber>;

    disableBalanceLimits(): Promise<BigNumber>;

    enableBalanceLimits(): Promise<BigNumber>;

    openChannel(_openRequest: Arrayish): Promise<BigNumber>;

    deposit(
      _channelId: Arrayish,
      _receiver: string,
      _transferFromAmount: BigNumberish
    ): Promise<BigNumber>;

    depositInBatch(
      _channelIds: Arrayish[],
      _receivers: string[],
      _transferFromAmounts: BigNumberish[]
    ): Promise<BigNumber>;

    snapshotStates(_signedSimplexStateArray: Arrayish): Promise<BigNumber>;

    intendWithdraw(
      _channelId: Arrayish,
      _amount: BigNumberish,
      _recipientChannelId: Arrayish
    ): Promise<BigNumber>;

    confirmWithdraw(_channelId: Arrayish): Promise<BigNumber>;

    vetoWithdraw(_channelId: Arrayish): Promise<BigNumber>;

    cooperativeWithdraw(
      _cooperativeWithdrawRequest: Arrayish
    ): Promise<BigNumber>;

    intendSettle(_signedSimplexStateArray: Arrayish): Promise<BigNumber>;

    clearPays(
      _channelId: Arrayish,
      _peerFrom: string,
      _payIdList: Arrayish
    ): Promise<BigNumber>;

    confirmSettle(_channelId: Arrayish): Promise<BigNumber>;

    cooperativeSettle(_settleRequest: Arrayish): Promise<BigNumber>;

    migrateChannelTo(_migrationRequest: Arrayish): Promise<BigNumber>;

    migrateChannelFrom(
      _fromLedgerAddr: string,
      _migrationRequest: Arrayish
    ): Promise<BigNumber>;

    getSettleFinalizedTime(_channelId: Arrayish): Promise<BigNumber>;

    getTokenContract(_channelId: Arrayish): Promise<BigNumber>;

    getTokenType(_channelId: Arrayish): Promise<BigNumber>;

    getChannelStatus(_channelId: Arrayish): Promise<BigNumber>;

    getCooperativeWithdrawSeqNum(_channelId: Arrayish): Promise<BigNumber>;

    getTotalBalance(_channelId: Arrayish): Promise<BigNumber>;

    getBalanceMap(_channelId: Arrayish): Promise<BigNumber>;

    getChannelMigrationArgs(_channelId: Arrayish): Promise<BigNumber>;

    getPeersMigrationInfo(_channelId: Arrayish): Promise<BigNumber>;

    getDisputeTimeout(_channelId: Arrayish): Promise<BigNumber>;

    getMigratedTo(_channelId: Arrayish): Promise<BigNumber>;

    getStateSeqNumMap(_channelId: Arrayish): Promise<BigNumber>;

    getTransferOutMap(_channelId: Arrayish): Promise<BigNumber>;

    getNextPayIdListHashMap(_channelId: Arrayish): Promise<BigNumber>;

    getLastPayResolveDeadlineMap(_channelId: Arrayish): Promise<BigNumber>;

    getPendingPayOutMap(_channelId: Arrayish): Promise<BigNumber>;

    getWithdrawIntent(_channelId: Arrayish): Promise<BigNumber>;

    getChannelStatusNum(_channelStatus: BigNumberish): Promise<BigNumber>;

    getEthPool(): Promise<BigNumber>;

    getPayRegistry(): Promise<BigNumber>;

    getCelerWallet(): Promise<BigNumber>;

    getBalanceLimit(_tokenAddr: string): Promise<BigNumber>;

    getBalanceLimitsEnabled(): Promise<BigNumber>;
  };
}
