/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { PayRegistry } from "./PayRegistry";

export class PayRegistryFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PayRegistry {
    return new Contract(address, _abi, signerOrProvider) as PayRegistry;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "",
        type: "bytes32"
      }
    ],
    name: "payInfoMap",
    outputs: [
      {
        name: "amount",
        type: "uint256"
      },
      {
        name: "resolveDeadline",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "payId",
        type: "bytes32"
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256"
      },
      {
        indexed: false,
        name: "resolveDeadline",
        type: "uint256"
      }
    ],
    name: "PayInfoUpdate",
    type: "event"
  },
  {
    constant: true,
    inputs: [
      {
        name: "_payHash",
        type: "bytes32"
      },
      {
        name: "_setter",
        type: "address"
      }
    ],
    name: "calculatePayId",
    outputs: [
      {
        name: "",
        type: "bytes32"
      }
    ],
    payable: false,
    stateMutability: "pure",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_payHash",
        type: "bytes32"
      },
      {
        name: "_amt",
        type: "uint256"
      }
    ],
    name: "setPayAmount",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_payHash",
        type: "bytes32"
      },
      {
        name: "_deadline",
        type: "uint256"
      }
    ],
    name: "setPayDeadline",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_payHash",
        type: "bytes32"
      },
      {
        name: "_amt",
        type: "uint256"
      },
      {
        name: "_deadline",
        type: "uint256"
      }
    ],
    name: "setPayInfo",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_payHashes",
        type: "bytes32[]"
      },
      {
        name: "_amts",
        type: "uint256[]"
      }
    ],
    name: "setPayAmounts",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_payHashes",
        type: "bytes32[]"
      },
      {
        name: "_deadlines",
        type: "uint256[]"
      }
    ],
    name: "setPayDeadlines",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_payHashes",
        type: "bytes32[]"
      },
      {
        name: "_amts",
        type: "uint256[]"
      },
      {
        name: "_deadlines",
        type: "uint256[]"
      }
    ],
    name: "setPayInfos",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        name: "_payIds",
        type: "bytes32[]"
      },
      {
        name: "_lastPayResolveDeadline",
        type: "uint256"
      }
    ],
    name: "getPayAmounts",
    outputs: [
      {
        name: "",
        type: "uint256[]"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        name: "_payId",
        type: "bytes32"
      }
    ],
    name: "getPayInfo",
    outputs: [
      {
        name: "",
        type: "uint256"
      },
      {
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];
